// Course content data structure
// In production, this would come from your database

export interface Lesson {
  id: string;
  title: string;
  description: string;
  duration: string;
  videoUrl: string;
  thumbnailUrl?: string;
  isFree: boolean;
}

export interface Module {
  id: string;
  title: string;
  description: string;
  lessons: Lesson[];
}

export interface CourseContent {
  courseId: string;
  modules: Module[];
}

// Sample course content with real training videos
// Replace these URLs with your actual training video URLs
export const courseContent: Record<string, CourseContent> = {
  "velocity-system": {
    courseId: "velocity-system",
    modules: [
      {
        id: "vs-week-1",
        title: "Week 1: Foundation",
        description: "Building the foundation for arm health and velocity",
        lessons: [
          {
            id: "vs-1-1",
            title: "Program Overview & Assessment",
            description: "Learn how to assess your current throwing mechanics and set baseline measurements.",
            duration: "12 min",
            videoUrl: "https://www.youtube.com/watch?v=example1",
            isFree: true,
          },
          {
            id: "vs-1-2",
            title: "Arm Care Routine",
            description: "Daily arm care exercises to prevent injury and promote recovery.",
            duration: "15 min",
            videoUrl: "https://www.youtube.com/watch?v=example2",
            isFree: true,
          },
          {
            id: "vs-1-3",
            title: "Long Toss Protocol",
            description: "Proper long toss technique and progressive distance training.",
            duration: "18 min",
            videoUrl: "https://www.youtube.com/watch?v=example3",
            isFree: false,
          },
          {
            id: "vs-1-4",
            title: "Weighted Ball Introduction",
            description: "Safe introduction to weighted ball training.",
            duration: "14 min",
            videoUrl: "https://www.youtube.com/watch?v=example4",
            isFree: false,
          },
        ],
      },
      {
        id: "vs-week-2",
        title: "Week 2: Mechanics",
        description: "Developing efficient throwing mechanics",
        lessons: [
          {
            id: "vs-2-1",
            title: "Hip-Shoulder Separation",
            description: "Maximizing rotational power through proper sequencing.",
            duration: "16 min",
            videoUrl: "https://www.youtube.com/watch?v=example5",
            isFree: false,
          },
          {
            id: "vs-2-2",
            title: "Arm Path Optimization",
            description: "Creating an efficient arm path for velocity and health.",
            duration: "14 min",
            videoUrl: "https://www.youtube.com/watch?v=example6",
            isFree: false,
          },
          {
            id: "vs-2-3",
            title: "Lead Leg Block",
            description: "Using the lead leg to transfer energy up the chain.",
            duration: "12 min",
            videoUrl: "https://www.youtube.com/watch?v=example7",
            isFree: false,
          },
          {
            id: "vs-2-4",
            title: "Drill Combinations",
            description: "Putting it all together with compound drills.",
            duration: "20 min",
            videoUrl: "https://www.youtube.com/watch?v=example8",
            isFree: false,
          },
        ],
      },
      {
        id: "vs-week-3",
        title: "Week 3: Intensity",
        description: "Building arm strength and throwing intensity",
        lessons: [
          {
            id: "vs-3-1",
            title: "Pulldown Training",
            description: "Max effort throwing for velocity development.",
            duration: "15 min",
            videoUrl: "https://www.youtube.com/watch?v=example9",
            isFree: false,
          },
          {
            id: "vs-3-2",
            title: "Plyo Ball Routines",
            description: "Advanced weighted ball drills for power development.",
            duration: "18 min",
            videoUrl: "https://www.youtube.com/watch?v=example10",
            isFree: false,
          },
          {
            id: "vs-3-3",
            title: "Recovery Protocols",
            description: "Managing workload and optimizing recovery.",
            duration: "10 min",
            videoUrl: "https://www.youtube.com/watch?v=example11",
            isFree: false,
          },
          {
            id: "vs-3-4",
            title: "Progress Assessment",
            description: "Measuring gains and planning next phase.",
            duration: "12 min",
            videoUrl: "https://www.youtube.com/watch?v=example12",
            isFree: false,
          },
        ],
      },
    ],
  },
  "strength-conditioning": {
    courseId: "strength-conditioning",
    modules: [
      {
        id: "sc-week-1",
        title: "Week 1: Assessment & Movement",
        description: "Establishing baseline strength and movement patterns",
        lessons: [
          {
            id: "sc-1-1",
            title: "Strength Assessment",
            description: "Testing your current strength levels across key lifts.",
            duration: "20 min",
            videoUrl: "https://www.youtube.com/watch?v=sc1",
            isFree: true,
          },
          {
            id: "sc-1-2",
            title: "Movement Screening",
            description: "Identifying mobility limitations and imbalances.",
            duration: "15 min",
            videoUrl: "https://www.youtube.com/watch?v=sc2",
            isFree: true,
          },
          {
            id: "sc-1-3",
            title: "Squat Fundamentals",
            description: "Building a strong squat pattern from the ground up.",
            duration: "18 min",
            videoUrl: "https://www.youtube.com/watch?v=sc3",
            isFree: false,
          },
          {
            id: "sc-1-4",
            title: "Hinge Mechanics",
            description: "Deadlift and RDL technique for power development.",
            duration: "16 min",
            videoUrl: "https://www.youtube.com/watch?v=sc4",
            isFree: false,
          },
        ],
      },
      {
        id: "sc-week-2",
        title: "Week 2: Power Development",
        description: "Building explosive power for the diamond",
        lessons: [
          {
            id: "sc-2-1",
            title: "Olympic Lift Progressions",
            description: "Clean and snatch variations for baseball athletes.",
            duration: "22 min",
            videoUrl: "https://www.youtube.com/watch?v=sc5",
            isFree: false,
          },
          {
            id: "sc-2-2",
            title: "Medicine Ball Training",
            description: "Rotational power development with med balls.",
            duration: "14 min",
            videoUrl: "https://www.youtube.com/watch?v=sc6",
            isFree: false,
          },
          {
            id: "sc-2-3",
            title: "Plyometric Foundations",
            description: "Jump training for explosive lower body power.",
            duration: "16 min",
            videoUrl: "https://www.youtube.com/watch?v=sc7",
            isFree: false,
          },
        ],
      },
    ],
  },
  "speed-agility": {
    courseId: "speed-agility",
    modules: [
      {
        id: "sa-week-1",
        title: "Week 1: Sprint Mechanics",
        description: "Developing elite linear speed",
        lessons: [
          {
            id: "sa-1-1",
            title: "Sprint Posture & Arm Action",
            description: "The fundamentals of efficient sprinting.",
            duration: "14 min",
            videoUrl: "https://www.youtube.com/watch?v=sa1",
            isFree: true,
          },
          {
            id: "sa-1-2",
            title: "First Step Quickness",
            description: "Explosive starts and acceleration mechanics.",
            duration: "12 min",
            videoUrl: "https://www.youtube.com/watch?v=sa2",
            isFree: true,
          },
          {
            id: "sa-1-3",
            title: "Base Running Speed",
            description: "Applying sprint mechanics to the bases.",
            duration: "16 min",
            videoUrl: "https://www.youtube.com/watch?v=sa3",
            isFree: false,
          },
        ],
      },
      {
        id: "sa-week-2",
        title: "Week 2: Change of Direction",
        description: "Multi-directional speed for defensive excellence",
        lessons: [
          {
            id: "sa-2-1",
            title: "Lateral Movement Patterns",
            description: "Efficient side-to-side movement for infielders.",
            duration: "15 min",
            videoUrl: "https://www.youtube.com/watch?v=sa4",
            isFree: false,
          },
          {
            id: "sa-2-2",
            title: "Drop Step & Crossover",
            description: "Outfield-specific movement skills.",
            duration: "14 min",
            videoUrl: "https://www.youtube.com/watch?v=sa5",
            isFree: false,
          },
        ],
      },
    ],
  },
  // NEW COURSES FROM VAULT PDFs
  "arm-health-workload": {
    courseId: "arm-health-workload",
    modules: [
      {
        id: "ah-intro",
        title: "Executive Overview",
        description: "Understanding arm health as a performance system, not a medical reaction",
        lessons: [
          {
            id: "ah-1-1",
            title: "Arm Health Philosophy",
            description: "VAULT™ manages total throwing stress by controlling volume, intent, and recovery.",
            duration: "10 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "ah-1-2",
            title: "Key Performance Indicators",
            description: "Learn about Availability %, High-Intent Days, Recovery Compliance, and Velocity Stability.",
            duration: "12 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "ah-mobility",
        title: "Mobility & Activation",
        description: "Restore range of motion and prep stabilizers",
        lessons: [
          {
            id: "ah-2-1",
            title: "T-Spine Rotations & Shoulder CARs",
            description: "Mobility exercises to restore range of motion.",
            duration: "15 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ah-2-2",
            title: "Band ER & Serratus Wall Slides",
            description: "Activation exercises to prep stabilizers.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "ah-strength",
        title: "Arm Strength & Tissue Resilience",
        description: "Build tissue resilience through targeted strength work",
        lessons: [
          {
            id: "ah-3-1",
            title: "DB ER, Rows & Landmine Press",
            description: "Strength exercises for tissue resilience.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ah-3-2",
            title: "Eccentric Band ER & Reverse Throws",
            description: "Deceleration training to protect arm post-release.",
            duration: "15 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "ah-recovery",
        title: "Recovery Protocols",
        description: "Restore the nervous system and optimize recovery",
        lessons: [
          {
            id: "ah-4-1",
            title: "Breathing & Light Band Work",
            description: "Recovery techniques to restore the nervous system.",
            duration: "10 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ah-4-2",
            title: "Sleep Optimization for Athletes",
            description: "How sleep impacts arm health and performance.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "strength-power-system": {
    courseId: "strength-power-system",
    modules: [
      {
        id: "sp-foundation",
        title: "Force Category Foundations",
        description: "Understanding the key force categories for baseball performance",
        lessons: [
          {
            id: "sp-1-1",
            title: "Lower-Body Force Production",
            description: "Trap-bar deadlift, split squat, box squat for ground force production.",
            duration: "20 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "sp-1-2",
            title: "Rotational Power Transfer",
            description: "Med-ball scoop toss, shot-put throw for hip-to-torso power.",
            duration: "18 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "sp-decel",
        title: "Deceleration & Stability",
        description: "Braking, tissue protection, and force transfer",
        lessons: [
          {
            id: "sp-2-1",
            title: "Depth Drops & Eccentric Split Squats",
            description: "Deceleration training for braking and tissue protection.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "sp-2-2",
            title: "Pallof Press & Suitcase Carry",
            description: "Anti-rotation work for stability and force transfer.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "sp-inseason",
        title: "In-Season Training Model",
        description: "Maintain force output while managing fatigue during the season",
        lessons: [
          {
            id: "sp-3-1",
            title: "In-Season Programming Principles",
            description: "1-2 lifts per week with submaximal, high intent loading.",
            duration: "15 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "sp-3-2",
            title: "Priority: Deceleration & Recovery",
            description: "Maintaining durability while avoiding max effort lifting.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "sp-offseason",
        title: "Off-Season Training Model",
        description: "Build force capacity, power output, and structural resilience",
        lessons: [
          {
            id: "sp-4-1",
            title: "Off-Season Programming Principles",
            description: "3-4 lifts per week with progressive strength to power.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "sp-4-2",
            title: "Rotational & Acceleration Work",
            description: "Building force production and movement quality.",
            duration: "20 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "organizational-development": {
    courseId: "organizational-development",
    modules: [
      {
        id: "od-intro",
        title: "Executive Introduction",
        description: "Understanding organizational alignment in baseball development",
        lessons: [
          {
            id: "od-1-1",
            title: "The Core Problem: Misalignment",
            description: "Why standards that vary by coach or team make development fragile.",
            duration: "12 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "od-1-2",
            title: "The VAULT™ Five Pillars",
            description: "Velocity, Athleticism, Utility, Longevity, Transfer - the foundation of development.",
            duration: "15 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "od-alignment",
        title: "Organizational Alignment Model",
        description: "Creating consistency from leadership to athletes",
        lessons: [
          {
            id: "od-2-1",
            title: "The Alignment Hierarchy",
            description: "Ownership → Director of Player Development → Coaches → Athletes.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "od-2-2",
            title: "Consistent Development Standards",
            description: "Ensuring athletes receive the same development regardless of team or age group.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "od-decisions",
        title: "Decision-Making Framework",
        description: "The VAULT™ decision-making filter for organizational choices",
        lessons: [
          {
            id: "od-3-1",
            title: "The Three Filter Questions",
            description: "Does it align with the 5 pillars? Protect long-term development? Preserve system integrity?",
            duration: "10 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "od-3-2",
            title: "Applying the Filter in Practice",
            description: "Real-world examples of using the decision-making framework.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "pitcher-catcher-overlap": {
    courseId: "pitcher-catcher-overlap",
    modules: [
      {
        id: "pco-overview",
        title: "Policy Overview",
        description: "Managing dual-role athletes who pitch and catch",
        lessons: [
          {
            id: "pco-1-1",
            title: "Understanding Overlap Stress",
            description: "Why athletes who pitch and catch experience significantly higher throwing stress.",
            duration: "10 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "pco-1-2",
            title: "Monitoring & Limiting Overlap",
            description: "How overlap is monitored, limited, and adjusted throughout the season.",
            duration: "12 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "pco-rules",
        title: "Non-Negotiable Rules",
        description: "The essential policies for protecting dual-role athletes",
        lessons: [
          {
            id: "pco-2-1",
            title: "Same-Game & Recovery Rules",
            description: "No pitching and catching in the same game. Mandatory recovery after catching → pitching.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "pco-2-2",
            title: "Weekly Limits & Director Approval",
            description: "High-intent days capped per week. Director approval required for overlap.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "winning-athlete-mindset": {
    courseId: "winning-athlete-mindset",
    modules: [
      {
        id: "wam-intro",
        title: "Introduction & Program Goals",
        description: "Building elite confidence, mental toughness, and competitive resilience",
        lessons: [
          {
            id: "wam-1-1",
            title: "Program Overview",
            description: "A 10-week mental performance training system for elite competitors.",
            duration: "10 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "wam-1-2",
            title: "Weekly Structure",
            description: "Mental lessons, daily tasks, journal prompts, and weekly challenges.",
            duration: "8 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "wam-week1",
        title: "Week 1: Identity & Purpose",
        description: "Athletes perform best when they understand who they are",
        lessons: [
          {
            id: "wam-2-1",
            title: "Define Who You Are",
            description: "Creating your Athlete Identity Statement and long-term vision.",
            duration: "15 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "wam-2-2",
            title: "Champion Discipline Challenge",
            description: "Complete 1 full day of 'no excuses' discipline checklist.",
            duration: "10 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "wam-week2",
        title: "Week 2: Confidence & Self-Talk",
        description: "True confidence comes from preparation, repetition, and intentional self-talk",
        lessons: [
          {
            id: "wam-3-1",
            title: "The Confidence Equation",
            description: "Confidence = Reps + Preparation + Belief. Self-talk controls performance.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "wam-3-2",
            title: "Reframing Negative Thoughts",
            description: "Techniques for shifting internal language to elite patterns.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "wam-weeks3-10",
        title: "Weeks 3-10: Advanced Mindset Training",
        description: "Focus, pressure, resilience, leadership, and championship habits",
        lessons: [
          {
            id: "wam-4-1",
            title: "Focus & Emotional Control",
            description: "Developing focus and emotional control under pressure.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "wam-4-2",
            title: "Leadership & Champion Mindset",
            description: "Building leadership habits and a champion mindset.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "wam-4-3",
            title: "Performance Consistency",
            description: "Improve performance consistency and pre-game readiness.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "elite-mental-performance": {
    courseId: "elite-mental-performance",
    modules: [
      {
        id: "emp-pillars",
        title: "Mental Performance Pillars",
        description: "The five core pillars of championship-level mental strength",
        lessons: [
          {
            id: "emp-1-1",
            title: "The Five Pillars Overview",
            description: "Confidence, Focus, Emotional Speed, Self-Talk, and Competitive Identity.",
            duration: "12 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "emp-1-2",
            title: "Building Each Pillar",
            description: "How each pillar is built through repetition and proof.",
            duration: "15 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "emp-visualization",
        title: "Visualization & Self-Talk System",
        description: "5-minute daily routines and identity-based affirmations",
        lessons: [
          {
            id: "emp-2-1",
            title: "5-Minute Visualization Routine",
            description: "Daily visualization practice for pre-game mental preparation.",
            duration: "10 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "emp-2-2",
            title: "Identity-Based Affirmations",
            description: "Creating and using competitive self-talk: 'I attack, I compete, I finish.'",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "emp-2-3",
            title: "Confidence Anchors & Reset Words",
            description: "Pre-game visualization scripts and mental triggers.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "emp-emotional",
        title: "Emotional Speed & Reset System",
        description: "Recovering fast from mistakes with structured routines",
        lessons: [
          {
            id: "emp-3-1",
            title: "The 6-Second Reset Routine",
            description: "Mistake → Breath → Reset → Refocus pattern for quick recovery.",
            duration: "10 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "emp-3-2",
            title: "Performance Breathing",
            description: "Box breath, 4-2-6 breath, and emotional neutrality training.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "emp-10week",
        title: "10-Week Mindset Calendar",
        description: "Progressive mental performance training program",
        lessons: [
          {
            id: "emp-4-1",
            title: "Weeks 1-5: Foundation Building",
            description: "Confidence base, emotional speed, focus training, visualization, pressure work.",
            duration: "20 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "emp-4-2",
            title: "Weeks 6-10: Championship Performance",
            description: "Self-talk upgrade, competitive identity, mental toughness, consistency, testing.",
            duration: "22 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "elite-speed-agility": {
    courseId: "elite-speed-agility",
    modules: [
      {
        id: "esa-warmup",
        title: "Warmup & Activation System",
        description: "Preparing the body for high-level speed work",
        lessons: [
          {
            id: "esa-1-1",
            title: "Dynamic Warmup Protocol",
            description: "A-Skips, B-Skips, linear mobility drills.",
            duration: "12 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "esa-1-2",
            title: "Acceleration & Plyometric Prep",
            description: "Wall drive series, lean-fall sprints, pogo jumps, mini-hurdles.",
            duration: "15 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "esa-mechanics",
        title: "Sprint Mechanics",
        description: "Acceleration position and top-speed mechanics",
        lessons: [
          {
            id: "esa-2-1",
            title: "Acceleration Position",
            description: "45° forward lean, powerful knee punch technique.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "esa-2-2",
            title: "Top-Speed Position",
            description: "Tall posture, front-side mechanics, relaxed upper body.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "esa-12week",
        title: "12-Week Speed & Agility Calendar",
        description: "Progressive training from foundation to peak performance",
        lessons: [
          {
            id: "esa-3-1",
            title: "Weeks 1-4: Foundation Phase",
            description: "Acceleration foundation, stride projection, stride frequency, COD foundation.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "esa-3-2",
            title: "Weeks 5-8: Development Phase",
            description: "Agility angles, reactive speed, sprint efficiency, explosive power.",
            duration: "20 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "esa-3-3",
            title: "Weeks 9-12: Peak Phase",
            description: "Sport-speed application, peak speed, max COD ability, testing week.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "esa-drills",
        title: "Elite Drill Library",
        description: "Advanced drills for acceleration, agility, and reactive speed",
        lessons: [
          {
            id: "esa-4-1",
            title: "Acceleration Drills",
            description: "Wall drills, linear starts, hip projection techniques.",
            duration: "15 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "esa-4-2",
            title: "Agility & Reactive Drills",
            description: "Crossover steps, lateral transitions, mirror drills, reaction starts.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "elite-hitting-exit-velocity": {
    courseId: "elite-hitting-exit-velocity",
    modules: [
      {
        id: "ehev-warmup",
        title: "Warmup & Activation System",
        description: "Preparing for high-intent hitting work",
        lessons: [
          {
            id: "ehev-1-1",
            title: "Dynamic Warmup for Hitters",
            description: "Skips, hip mobility, med ball warmups.",
            duration: "12 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "ehev-1-2",
            title: "Bat Speed & Rotational Prep",
            description: "Top-hand/bottom-hand work, bat path drills, mini-band rotations.",
            duration: "14 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "ehev-mechanics",
        title: "Advanced Swing Mechanics",
        description: "Hip-rotation sequence and elite barrel path",
        lessons: [
          {
            id: "ehev-2-1",
            title: "Hip-Rotation Sequence",
            description: "Lead hip fires first, torso and shoulders follow for maximum power.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ehev-2-2",
            title: "Elite Barrel Path",
            description: "Smooth on-plane entry with slight upward attack angle.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "ehev-12week",
        title: "12-Week Exit Velocity Calendar",
        description: "Progressive training from foundation to max EV",
        lessons: [
          {
            id: "ehev-3-1",
            title: "Weeks 1-4: Foundation Phase",
            description: "Posture & base, sequencing, barrel path, bat speed intro.",
            duration: "20 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ehev-3-2",
            title: "Weeks 5-8: Power Development Phase",
            description: "Rotation power, intent training, game-speed approach, gap-to-gap power.",
            duration: "22 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ehev-3-3",
            title: "Weeks 9-12: Peak Performance Phase",
            description: "Advanced barrel control, bat speed peak, max EV training, testing week.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "ehev-drills",
        title: "Elite Hitting Drill Library",
        description: "Advanced drills for bat speed and exit velocity",
        lessons: [
          {
            id: "ehev-4-1",
            title: "Coil Load & Launch Sequence",
            description: "Building the foundation for explosive swings.",
            duration: "15 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ehev-4-2",
            title: "Overspeed & Overload Training",
            description: "Using bat speed tools to increase exit velocity.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ehev-4-3",
            title: "Intent Training Sessions",
            description: "High intent tee and front toss for maximum power output.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  // NEW PITCHING COURSES
  "pitching-velocity-8week": {
    courseId: "pitching-velocity-8week",
    modules: [
      {
        id: "pv-warmup",
        title: "Warmup & Activation System",
        description: "Prepare the body for safe, effective throwing",
        lessons: [
          {
            id: "pv-1-1",
            title: "Dynamic Warmup Protocol",
            description: "High knees, A-skips, leg swings for movement prep.",
            duration: "10 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "pv-1-2",
            title: "Arm & Mobility Prep",
            description: "Band external rotations, T-Y-Ws, scap activations, thoracic rotations, hip openers.",
            duration: "12 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "pv-mechanics",
        title: "Mechanics Foundations",
        description: "Balance position and stride mechanics",
        lessons: [
          {
            id: "pv-2-1",
            title: "Balance Position",
            description: "Establishing proper posture and balance at the top of the delivery.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "pv-2-2",
            title: "Stride Position",
            description: "Developing proper stride mechanics for power and direction.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "pv-8week",
        title: "8-Week Velocity Calendar",
        description: "Progressive training from foundation to velocity testing",
        lessons: [
          {
            id: "pv-3-1",
            title: "Weeks 1-4: Foundation Phase",
            description: "Posture & balance, hip lead, separation, arm speed with plyo balls.",
            duration: "20 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "pv-3-2",
            title: "Weeks 5-8: Development Phase",
            description: "Recovery strength, mound blend, command + intent, velocity test.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "pv-drills",
        title: "Drill Library",
        description: "Essential drills for pitching development",
        lessons: [
          {
            id: "pv-4-1",
            title: "Pivot Picks & Rocker Throws",
            description: "Trains arm-path efficiency and improves sequencing.",
            duration: "15 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "pv-4-2",
            title: "Step-Behind & Reverse Throws",
            description: "Develops momentum and builds arm deceleration.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "pv-4-3",
            title: "Connection Ball Work",
            description: "Maintains alignment throughout the delivery.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "elite-pitching-12week": {
    courseId: "elite-pitching-12week",
    modules: [
      {
        id: "ep-warmup",
        title: "Elite Warmup & Activation System",
        description: "Advanced preparation for high-intent throwing",
        lessons: [
          {
            id: "ep-1-1",
            title: "Dynamic Warmup & Sprint Buildups",
            description: "A-skips, reverse skips, sprint buildups for explosive prep.",
            duration: "12 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "ep-1-2",
            title: "Arm Activation & Hip Mobility",
            description: "Band ER/IR, scap loads, rebounders, 90/90 mobility, hip hike drills.",
            duration: "15 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "ep-mechanics",
        title: "Advanced Mechanics",
        description: "Hip-to-shoulder separation and elite arm path",
        lessons: [
          {
            id: "ep-2-1",
            title: "Hip-to-Shoulder Separation",
            description: "Hip lead, delayed trunk, stored energy release for maximum velocity.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ep-2-2",
            title: "Elite Arm Path",
            description: "Smooth scap load, clean layback angle for efficient arm action.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "ep-12week",
        title: "12-Week Velocity Calendar",
        description: "Progressive training from foundation to peak velocity",
        lessons: [
          {
            id: "ep-3-1",
            title: "Weeks 1-4: Foundation Phase",
            description: "Posture & balance, hip lead mastery, separation, arm speed.",
            duration: "22 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ep-3-2",
            title: "Weeks 5-8: Development Phase",
            description: "Lower half power, full delivery blend, command precision, velocity block.",
            duration: "24 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ep-3-3",
            title: "Weeks 9-12: Peak Phase",
            description: "Mound work, competitive bullpens, peak velocity, testing week.",
            duration: "20 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "ep-drills",
        title: "Elite Drill Library",
        description: "Advanced drills for velocity development",
        lessons: [
          {
            id: "ep-4-1",
            title: "Advanced Plyo Ball Progressions",
            description: "High-level plyo ball work for arm speed development.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ep-4-2",
            title: "Heavy Med Ball Rotational Throws",
            description: "Building rotational power and hip-to-torso transfer.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ep-4-3",
            title: "Competitive Bullpen Structure",
            description: "Game-like bullpen sessions with intent and approach training.",
            duration: "20 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "ep-strength",
        title: "Strength & Power Add-On",
        description: "Supporting strength work for pitchers",
        lessons: [
          {
            id: "ep-5-1",
            title: "Lower Half Power Development",
            description: "Force production patterns for explosive delivery.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ep-5-2",
            title: "Recovery & Arm Care System",
            description: "Post-throw protocols and arm health maintenance.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  // NEW CATCHER COURSES
  "youth-catcher-8week": {
    courseId: "youth-catcher-8week",
    modules: [
      {
        id: "yc-warmup",
        title: "Warmup & Activation System",
        description: "Prepare young catchers for skill work",
        lessons: [
          {
            id: "yc-1-1",
            title: "Dynamic Warmup for Catchers",
            description: "Hip mobility, deep squat holds, lateral steps.",
            duration: "10 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "yc-1-2",
            title: "Receiving & Throwing Prep",
            description: "Tennis ball soft-hand drills, glove pocket work, band activation.",
            duration: "12 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "yc-receiving",
        title: "Receiving Foundations",
        description: "Building proper receiving mechanics",
        lessons: [
          {
            id: "yc-2-1",
            title: "Stance & Glove Position",
            description: "Low stance, quiet glove, hinge-loaded hips.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "yc-2-2",
            title: "Soft Hands Development",
            description: "Tennis ball drills for quiet, efficient receiving.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "yc-blocking",
        title: "Blocking Fundamentals",
        description: "Safe and effective blocking technique",
        lessons: [
          {
            id: "yc-3-1",
            title: "Knee-Replace Drill Progression",
            description: "Building proper blocking form with chest forward, knees down.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "yc-3-2",
            title: "Angle Blocks",
            description: "Blocking pitches to both sides of the plate.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "yc-footwork",
        title: "Footwork & Throwing",
        description: "Developing efficient transfers and throws",
        lessons: [
          {
            id: "yc-4-1",
            title: "Step-Replace Footwork",
            description: "Efficient foot transfer for quick throws.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "yc-4-2",
            title: "Safe Throwing Mechanics",
            description: "Age-appropriate throwing technique from the crouch.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "elite-catcher-12week": {
    courseId: "elite-catcher-12week",
    modules: [
      {
        id: "ec-warmup",
        title: "Warmup & Activation System",
        description: "Prepare for elite-level catching work",
        lessons: [
          {
            id: "ec-1-1",
            title: "Dynamic Warmup for Catchers",
            description: "Hip mobility, deep squat holds, lateral steps for catcher-specific prep.",
            duration: "12 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "ec-1-2",
            title: "Receiving, Blocking & Throwing Prep",
            description: "Glove pocket work, knee drops, chest angles, pivot throws, wrist flicks.",
            duration: "15 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "ec-mechanics",
        title: "Elite Catching Mechanics",
        description: "Professional-level receiving, blocking, and pop-time footwork",
        lessons: [
          {
            id: "ec-2-1",
            title: "Receiving Stance & Quiet Glove",
            description: "Low stance, quiet glove, hinge-loaded hips for elite presentation.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ec-2-2",
            title: "Blocking Form",
            description: "Chest forward, knees down, glove protects for maximum coverage.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ec-2-3",
            title: "Pop-Time Footwork",
            description: "Step → Replace → Throw pattern for efficient transfers.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "ec-12week",
        title: "12-Week Catcher Calendar",
        description: "Progressive training from foundation to elite pop-time",
        lessons: [
          {
            id: "ec-3-1",
            title: "Weeks 1-4: Foundation Phase",
            description: "Receiving foundation, pocket control, blocking foundation, advanced blocks.",
            duration: "22 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ec-3-2",
            title: "Weeks 5-8: Development Phase",
            description: "Transfer speed, footwork speed, throwing mechanics, pop-time focus.",
            duration: "24 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ec-3-3",
            title: "Weeks 9-12: Peak Phase",
            description: "Multi-angle work, game-speed receiving, elite pop-time, testing week.",
            duration: "20 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "ec-drills",
        title: "Elite Drill Library",
        description: "Advanced drills for all catching skills",
        lessons: [
          {
            id: "ec-4-1",
            title: "Elite Framing Patterns",
            description: "Stick frames, quiet presentation, pocket stability.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ec-4-2",
            title: "Reaction Blocking Drills",
            description: "Lateral reads and reaction blocks for game situations.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ec-4-3",
            title: "Pop-Time Velocity Footwork",
            description: "High intent pop-time sessions with timed reps.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "ec-strength",
        title: "Strength, Mobility & Durability",
        description: "Catcher-specific physical development",
        lessons: [
          {
            id: "ec-5-1",
            title: "Catcher-Specific Strength",
            description: "Trap bar deadlift, squat variations, core anti-rotation holds.",
            duration: "20 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ec-5-2",
            title: "Hip & Ankle Mobility",
            description: "Ankle mobility, hip internal/external rotation, T-spine rotation.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "vault-catcher-complete": {
    courseId: "vault-catcher-complete",
    modules: [
      {
        id: "vcc-intro",
        title: "Introduction & Testing",
        description: "Program overview and baseline testing protocol",
        lessons: [
          {
            id: "vcc-1-1",
            title: "Program Introduction",
            description: "Building complete, high-performance catchers with all components.",
            duration: "10 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "vcc-1-2",
            title: "Week 0 Testing Protocol",
            description: "Pop time, receiving, blocking, mobility, and strength baseline tests.",
            duration: "18 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "vcc-weekly",
        title: "Weekly Training Structure",
        description: "4 core catcher days + 1 strength day per week",
        lessons: [
          {
            id: "vcc-2-1",
            title: "Day 1: Receiving & Framing",
            description: "Pocket control, quiet glove work, one-knee receiving mechanics.",
            duration: "20 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "vcc-2-2",
            title: "Day 2: Blocking & Lateral Mobility",
            description: "Drop-and-block, reaction blocks, lateral explosion.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "vcc-2-3",
            title: "Day 3: Footwork, Transfer & Throwing",
            description: "Crouch-to-throw, transfer speed, throwing mechanics, velocity buildups.",
            duration: "22 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "vcc-2-4",
            title: "Day 4: Game-Calling & Situational IQ",
            description: "Pitch sequencing, reading hitters, leadership development.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "vcc-2-5",
            title: "Day 5: Strength & Mobility",
            description: "Core, hips, lower-body power for catcher durability.",
            duration: "20 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "vcc-goals",
        title: "Program Goals & Outcomes",
        description: "Target improvements for elite catcher development",
        lessons: [
          {
            id: "vcc-3-1",
            title: "Pop Time & Throwing Velocity",
            description: "Target improvement: 0.15-0.30 seconds, increased crouch velocity.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "vcc-3-2",
            title: "Receiving, Framing & Blocking",
            description: "Improve pocket stability, elite blocking technique, lateral reaction speed.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "vcc-3-3",
            title: "Leadership & Game Management",
            description: "Develop game-calling IQ, pitch sequencing, and leadership.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "annual-development-calendar": {
    courseId: "annual-development-calendar",
    modules: [
      {
        id: "adc-overview",
        title: "Executive Overview",
        description: "Understanding the annual development calendar",
        lessons: [
          {
            id: "adc-1-1",
            title: "Calendar Purpose & Philosophy",
            description: "Aligns training priorities, workloads, and recovery across the entire year to prevent overuse and improve performance timing.",
            duration: "10 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "adc-1-2",
            title: "Annual Development Phases Overview",
            description: "Post-Season Reset, Off-Season Build, Pre-Season Ramp, In-Season Compete, and Transition/Review.",
            duration: "12 min",
            videoUrl: "",
            isFree: true,
          },
        ],
      },
      {
        id: "adc-postseason",
        title: "Post-Season Reset Phase",
        description: "Recovery, mobility, and assessment (4-6 weeks)",
        lessons: [
          {
            id: "adc-2-1",
            title: "Post-Season Recovery Protocol",
            description: "Mobility, light strength, arm recovery. No velocity chasing occurs.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "adc-2-2",
            title: "Post-Season KPIs",
            description: "ROM restored, soreness resolved, low load movement quality.",
            duration: "10 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "adc-offseason",
        title: "Off-Season Build Phase",
        description: "Strength, power, and arm capacity (8-12 weeks)",
        lessons: [
          {
            id: "adc-3-1",
            title: "Off-Season Training Structure",
            description: "3-4 strength sessions/week with progressive, structured intent throwing.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "adc-3-2",
            title: "Off-Season KPIs",
            description: "Force gains, stable recovery, building the physical engine for the year.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "adc-preseason",
        title: "Pre-Season Ramp Phase",
        description: "Velocity transfer and workload prep (6-8 weeks)",
        lessons: [
          {
            id: "adc-4-1",
            title: "Pre-Season Training Bridge",
            description: "Reduced volume, high intent strength. Zone 2-3 planned throwing.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "adc-4-2",
            title: "Pre-Season KPIs",
            description: "Velocity stability, command development, competition readiness.",
            duration: "10 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "adc-inseason",
        title: "In-Season & Transition Phases",
        description: "Competition maintenance and review",
        lessons: [
          {
            id: "adc-5-1",
            title: "In-Season Competition Phase",
            description: "1-2 strength sessions/week, competition-based throwing. Availability % and fatigue control.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "adc-5-2",
            title: "Transition & Review Phase",
            description: "Assessment, planning, light movement, optional catch play. Data review completed.",
            duration: "10 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
};

export const getCourseContent = (courseId: string): CourseContent | undefined => {
  return courseContent[courseId];
};
