// Softball-specific course data
// This module mirrors the baseball course structure but with softball-specific content

import { CourseContent } from "@/lib/courseData";

export const softballCourseContent: Record<string, CourseContent> = {
  "fastpitch-pitching-system": {
    courseId: "fastpitch-pitching-system",
    modules: [
      {
        id: "fp-week-1",
        title: "Week 1: Fastpitch Foundations",
        description: "Building the foundation for windmill pitching mechanics",
        lessons: [
          {
            id: "fp-1-1",
            title: "Windmill Mechanics Overview",
            description: "Understanding the biomechanics of the windmill pitch and proper body alignment.",
            duration: "14 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "fp-1-2",
            title: "Stride & Drive Mechanics",
            description: "Developing a powerful stride with proper push-off and landing mechanics.",
            duration: "16 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "fp-1-3",
            title: "Wrist Snap & Release Point",
            description: "Mastering the wrist snap for maximum velocity and spin.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "fp-1-4",
            title: "Arm Circle Timing",
            description: "Coordinating the arm circle with lower body mechanics for power transfer.",
            duration: "15 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "fp-week-2",
        title: "Week 2: Pitch Arsenal Development",
        description: "Building a complete pitch repertoire",
        lessons: [
          {
            id: "fp-2-1",
            title: "Fastball Command",
            description: "Locating the fastball to all quadrants of the strike zone.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "fp-2-2",
            title: "Change-Up Development",
            description: "Developing an effective change-up with proper arm speed deception.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "fp-2-3",
            title: "Rise Ball Mechanics",
            description: "Mastering the rise ball with proper backspin and release angle.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "fp-2-4",
            title: "Drop Ball & Curve",
            description: "Developing breaking pitches with consistent spin and movement.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "fp-week-3",
        title: "Week 3: Velocity & Durability",
        description: "Increasing pitch speed while maintaining arm health",
        lessons: [
          {
            id: "fp-3-1",
            title: "Velocity Development Drills",
            description: "Targeted drills to increase fastpitch velocity safely.",
            duration: "20 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "fp-3-2",
            title: "Arm Care for Pitchers",
            description: "Softball-specific arm care routine for windmill pitchers.",
            duration: "15 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "fp-3-3",
            title: "Game Situation Pitching",
            description: "Pitch sequencing and strategy for different counts and situations.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "softball-hitting-system": {
    courseId: "softball-hitting-system",
    modules: [
      {
        id: "sh-week-1",
        title: "Week 1: Hitting Foundations",
        description: "Building a repeatable, powerful softball swing",
        lessons: [
          {
            id: "sh-1-1",
            title: "Stance & Load Mechanics",
            description: "Setting up for success with proper stance width, weight distribution, and load timing.",
            duration: "14 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "sh-1-2",
            title: "Rotational vs. Linear Hitting",
            description: "Understanding swing plane options and when to use each approach.",
            duration: "16 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "sh-1-3",
            title: "Contact Point Zones",
            description: "Identifying optimal contact points for inside, middle, and outside pitches.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "sh-week-2",
        title: "Week 2: Advanced Hitting",
        description: "Developing power and situational hitting skills",
        lessons: [
          {
            id: "sh-2-1",
            title: "Slap Hitting Fundamentals",
            description: "Mastering the slap hit for speed-based offense and bunting for base hits.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "sh-2-2",
            title: "Power Hitting Development",
            description: "Generating backspin and lift for extra-base hits.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "sh-2-3",
            title: "Timing the Rise Ball",
            description: "Adjustments for handling rise balls, drop balls, and off-speed pitches.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "softball-fielding-system": {
    courseId: "softball-fielding-system",
    modules: [
      {
        id: "sf-week-1",
        title: "Week 1: Infield Play",
        description: "Developing elite infield skills for softball",
        lessons: [
          {
            id: "sf-1-1",
            title: "Ready Position & First Step",
            description: "Athletic stance and explosive first-step reactions for infielders.",
            duration: "12 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "sf-1-2",
            title: "Backhand & Forehand Plays",
            description: "Technique for fielding balls to both sides with clean transfers.",
            duration: "15 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "sf-1-3",
            title: "Double Play Turns",
            description: "Footwork and feeds for turning double plays from all infield positions.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
      {
        id: "sf-week-2",
        title: "Week 2: Outfield & Catching",
        description: "Position-specific defensive development",
        lessons: [
          {
            id: "sf-2-1",
            title: "Outfield Routes & Jumps",
            description: "Reading the ball off the bat and taking efficient routes.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "sf-2-2",
            title: "Catching: Framing & Blocking",
            description: "Softball-specific catching techniques including framing rise balls.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "sf-2-3",
            title: "Throwing from Position",
            description: "Quick transfers and accurate throws from every defensive position.",
            duration: "15 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "softball-baserunning": {
    courseId: "softball-baserunning",
    modules: [
      {
        id: "sb-week-1",
        title: "Week 1: Speed & Stealing",
        description: "Developing elite baserunning skills for softball",
        lessons: [
          {
            id: "sb-1-1",
            title: "Leadoff & Timing",
            description: "Understanding softball leadoff rules and timing the pitcher's release.",
            duration: "12 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "sb-1-2",
            title: "Stealing Mechanics",
            description: "First step explosion and running form for stealing bases.",
            duration: "14 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "sb-1-3",
            title: "Sliding Techniques",
            description: "Pop-up slides, hook slides, and headfirst decisions.",
            duration: "12 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "sb-1-4",
            title: "Situational Baserunning",
            description: "Reading the defense, tagging up, and advancing on wild pitches.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
  "softball-strength-conditioning": {
    courseId: "softball-strength-conditioning",
    modules: [
      {
        id: "ssc-week-1",
        title: "Week 1: Softball-Specific Strength",
        description: "Building functional strength for softball athletes",
        lessons: [
          {
            id: "ssc-1-1",
            title: "Lower Body Power",
            description: "Squats, lunges, and plyometrics designed for softball movements.",
            duration: "20 min",
            videoUrl: "",
            isFree: true,
          },
          {
            id: "ssc-1-2",
            title: "Rotational Power for Hitters",
            description: "Med ball and cable work for generating bat speed and exit velocity.",
            duration: "16 min",
            videoUrl: "",
            isFree: false,
          },
          {
            id: "ssc-1-3",
            title: "Pitching-Specific Conditioning",
            description: "Shoulder stability and core endurance for pitchers.",
            duration: "18 min",
            videoUrl: "",
            isFree: false,
          },
        ],
      },
    ],
  },
};

// Softball course catalog for the Courses page
export const softballTrainingSystems = [
  {
    id: "fastpitch-pitching",
    pillar: "V",
    title: "Fastpitch Pitching System",
    description: "Master windmill mechanics, develop a complete pitch arsenal, and increase velocity through softball-specific training.",
    duration: "10 Weeks",
    modules: 3,
    color: "from-purple-500 to-pink-500",
    bgColor: "bg-purple-500/10",
    textColor: "text-purple-500",
    metrics: ["Pitch Speed", "Spin Rate", "Rise Ball Velo", "Command %"],
    isNew: true,
    courseId: "fastpitch-pitching-system",
  },
  {
    id: "softball-hitting",
    pillar: "A",
    title: "Softball Hitting System",
    description: "Build a powerful, repeatable swing with slap hitting, power hitting, and timing adjustments for softball pitching.",
    duration: "8 Weeks",
    modules: 2,
    color: "from-amber-500 to-orange-500",
    bgColor: "bg-amber-500/10",
    textColor: "text-amber-500",
    metrics: ["Exit Velocity", "Bat Speed", "Slap Speed", "Contact Rate"],
    isNew: true,
    courseId: "softball-hitting-system",
  },
  {
    id: "softball-fielding",
    pillar: "U",
    title: "Softball Fielding System",
    description: "Elite defensive skills for every position including infield play, outfield routes, and catching techniques.",
    duration: "6 Weeks",
    modules: 2,
    color: "from-green-500 to-emerald-500",
    bgColor: "bg-green-500/10",
    textColor: "text-green-500",
    metrics: ["Throw Velocity", "Reaction Time", "Range Factor", "Fielding %"],
    isNew: true,
    courseId: "softball-fielding-system",
  },
];

export const softballAdditionalSystems = [
  {
    pillar: "L",
    title: "Softball Arm Health",
    description: "Windmill pitcher-specific arm care and shoulder stability",
    color: "text-purple-400",
  },
  {
    pillar: "T",
    title: "Baserunning System",
    description: "Speed, stealing, and situational baserunning for softball",
    color: "text-amber-400",
  },
  {
    pillar: "S",
    title: "Strength & Conditioning",
    description: "Softball-specific strength, power, and conditioning programs",
    color: "text-green-400",
  },
];
