// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-upcoming-tryouts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-upcoming-tryouts.ts
var list_upcoming_tryouts_default = defineTool({
  name: "list_upcoming_tryouts",
  title: "List upcoming tryouts",
  description: "List published Vault tryout events that have not started yet, with date, age group, location and price.",
  inputSchema: {
    limit: z.number().int().optional().describe("Maximum number of events to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tryout_events").select("id, name, age_group, starts_at, ends_at, location_name, address, price_cents, capacity, description, status").eq("status", "published").gte("starts_at", (/* @__PURE__ */ new Date()).toISOString()).order("starts_at", { ascending: true }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tryouts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-camps.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_camps_default = defineTool2({
  name: "list_camps",
  title: "List camps",
  description: "List Vault camps with pricing and registration windows.",
  inputSchema: {
    limit: z2.number().int().optional().describe("Maximum number of camps to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("camps").select("id, name, description, weekly_price_cents, full_pass_price_cents, status, registration_opens_at, registration_closes_at").order("registration_opens_at", { ascending: true, nullsFirst: false }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { camps: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Get my athlete profile",
  description: "Get the signed-in user's Vault athlete profile: position, class year, physical measurables, sport and recruiting targets.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "display_name, bio, sport_type, position, secondary_positions, age_group, graduation_year, height_inches, weight_lbs, throwing_arm, batting_side, sixty_yard_dash, academic_gpa, intended_major, division_target, target_schools"
    ).eq("user_id", ctx.getUserId() ?? "").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found for this account." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/update-my-profile.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var update_my_profile_default = defineTool4({
  name: "update_my_profile",
  title: "Update my athlete profile",
  description: "Update fields on the signed-in user's Vault athlete profile. Only the fields provided are changed.",
  inputSchema: {
    position: z3.string().optional().describe("Primary position."),
    graduation_year: z3.number().int().optional().describe("High school graduation year."),
    height_inches: z3.number().int().optional(),
    weight_lbs: z3.number().int().optional(),
    throwing_arm: z3.string().optional().describe("R or L."),
    batting_side: z3.string().optional().describe("R, L or S."),
    academic_gpa: z3.number().optional(),
    intended_major: z3.string().optional(),
    division_target: z3.string().optional().describe("Target level, e.g. D1, D2, D3, NAIA, JUCO."),
    target_schools: z3.array(z3.string()).optional().describe("List of target school names."),
    bio: z3.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const patch = Object.fromEntries(
      Object.entries(input).filter(([, v]) => v !== void 0 && v !== null)
    );
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "No fields provided to update." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").update(patch).eq("user_id", ctx.getUserId() ?? "").select("display_name, position, graduation_year, height_inches, weight_lbs, throwing_arm, batting_side, academic_gpa, intended_major, division_target, target_schools, bio");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? {}, null, 2) }],
      structuredContent: { profile: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/list-my-team-registrations.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_my_team_registrations_default = defineTool5({
  name: "list_my_team_registrations",
  title: "List my team registrations",
  description: "List Vault team registrations tied to the signed-in user's email, including team level, payment plan and payment status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return { content: [{ type: "text", text: "No email on this account." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("team_registrations").select(
      "id, team_level, tier, payment_plan, annual_tuition_cents, deposit_cents, installment_count, installment_cents, amount_paid_cents, status, player_first_name, player_last_name, player_position, created_at, paid_at"
    ).eq("parent_email", email).order("created_at", { ascending: false }).limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { registrations: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hhvdxkxaiauzikavtpuj";
var mcp_default = defineMcp({
  name: "vault-os",
  title: "VAULT OS",
  version: "0.1.0",
  instructions: "Tools for VAULT OS, a baseball and softball athlete development platform. Use `list_upcoming_tryouts` and `list_camps` for open events, `get_my_profile` / `update_my_profile` for the signed-in athlete's profile, and `list_my_team_registrations` for the family's team registrations and payment status.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_upcoming_tryouts_default, list_camps_default, get_my_profile_default, update_my_profile_default, list_my_team_registrations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
