REVOKE EXECUTE ON FUNCTION public.create_reservation_atomic(UUID, UUID, TIMESTAMPTZ, TIMESTAMPTZ, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_reservation_atomic(UUID, UUID, TIMESTAMPTZ, TIMESTAMPTZ, TEXT, TEXT, TEXT, TEXT) TO authenticated;

REVOKE EXECUTE ON FUNCTION public.preview_recurring_conflicts(UUID, UUID, TIMESTAMPTZ, TIMESTAMPTZ, TEXT, DATE) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.preview_recurring_conflicts(UUID, UUID, TIMESTAMPTZ, TIMESTAMPTZ, TEXT, DATE) TO authenticated;